[package]
name = "fastrparallel"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastrparallel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18"
reqwest = "0.11"
tokio = { version = "1.28", features = ["rt-multi-thread", "macros"] }
once_cell = "1.17"
futures = "0.3"
